### ISSUE TITLE
Glossary issues (TS and Dart)

### ISSUE THREAD

**Issue by chalin** [angular/angular.io#2036]
- [x] Drop doc regions in favor of ifDocs mixin and blocks - #2100.
 - [x] Cleanup hard coded links to TS docs (#1838).
 - [x] Ensure that no broken links remain (TS & Dart) whether the guide is accessed from `latest` or `latest/guide`. (#1123)

**Comment by chalin** [comment]
There are no broken links in the Dart docs. A separate issue has been opened to track the new TS/JS broken links, #2150.
