### ISSUE TITLE
[Dart] resync Dart .jade files, post-TS-RC5

### ISSUE THREAD

**Issue by chalin** [angular/angular.io#2077]
Follow up to #2043.
- [x] guide/architecture.jade
- [ ] guide/attribute-directives.jade
- [ ] guide/component-styles.jade
- [x] guide/dependency-injection.jade
- [ ] guide/displaying-data.jade
- [x] guide/hierarchical-dependency-injection.jade - #2080
- [x] guide/lifecycle-hooks.jade - #2141
- [x] guide/pipes.jade
- [x] guide/security.jade
- [ ] guide/server-communication.jade
- [x] guide/structural-directives.jade
- [x] guide/template-syntax.jade - #2121
- [x] quickstart.jade - #2078, #2089
- [x] tutorial/toh-pt6.jade - #2095

**Comment by Foxandxss** [comment]
Closing this, if that is a mistake, we reopen.

**Comment by chalin** [comment]
Yes, closing it now is fine. I've migrated the issue to https://github.com/dart-lang/site-webdev/issues/368.
